[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "paste2audio"
version = "0.1.0"
dependencies = []

[project.scripts]
paste2audio = "paste2audio.main:main"


